spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: aa1237113

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


itemImgLocation = /Users/hyeonseung/Desktop/shop/item
uploadPath=file:/Users/hyeonseung/Desktop/shop



logging.level:
  org.hibernate.SQL: debug
